"""coloured-noise-generator
Created on Tue Feb  6 16:23:46 2018

@author: michael stephens

Program to take signal in time domain from *.txt file in same directory and
apply noise. Output is a .txt file in time domain. 

Input signal should contain time and signal amplitudes in same file.

Program assumes that the file H1-PSD.txt is in same directory as 
coloured-noise-generator.py, this is generated by noise-psd-ligoH1-GW150914
"""

import numpy as np
import numpy.fft as fft


#load noise psd
ligo_psd = np.loadtxt('H1-PSD.txt')
nf = ligo_psd[0, :]
xf_n = 1e23*np.sqrt(ligo_psd[1, :])

#load signal from *.txt file, checking user input
filename = input('Enter file name (including \".txt\"): ')
while 1:
    try:
        signal = np.loadtxt(filename)
        break
    except FileNotFoundError:
        print('File not found, please try again... ')

t = signal[0, :]
h = signal[1, :]


N = len(h)
Ts = t[1]-t[0]

hf = abs(2/N*fft.rfft(h)) # convert to freq domain
xf_h = fft.rfftfreq(N, Ts)


#ensure both have same length in the frequency domain
if len(hf) < len(nf):
    hf = np.interp(xf_n, xf_h, hf)
    xf = xf_n
elif len(hf) > len(nf):
    nf = np.interp(xf_h, xf_n, nf)
    xf = xf_h


df = hf*nf







